### PR TITLE
Redmine and Git task (Second Day)

### PR DESCRIPTION
**Pull request by DevangDabhi**

### CODE REVIEW

**Comment by radixdt12020** [comment]
Create yourname folder in day2  and keep files in main branch

**Comment by DevangDabhi** [comment]
Good afternoon ma'am
I am facing some issues in This
And also I am not able to send pull request of day 3
Thank you

**Comment by radixdt12020** [comment]
please refer task id from redmine not like #1 and #2. resolve conflict. As taught in the morning

**Comment by DevangDabhi** [comment]
Good Afternoon mam
Conflict is successfully resolved.
Thank you

**Pull request closed without merging**
