### PR TITLE
A pool request after solving issues in git repository

### PR DESCRIPTION
**Pull request by anujpal82**

### CODE REVIEW

**Review by MilitPanchasara — COMMENTED** [review]
Day9 => No assignment files.

**Review by MilitPanchasara — COMMENTED** [review]
Day11 => Task incomplete.
Day12 => Image folder missing.
Day13 => No files
Day14 => Incomplete task, check all the navigation links, dont open day9/10 task in new window

**Review by MilitPanchasara — COMMENTED** [review]
Day15 => Use buttons instead of input tags for operations. Code should not calculate value if no input is given.

**Comment by radixdt12020** [comment]
Kindly provide meaning name

**Pull request merged**
