### PR TITLE
day16 and day15 task completed (REFS: #98 and fixes #98)

### PR DESCRIPTION
**Pull request by NirbhayDubey**

### CODE REVIEW

**Review by MilitPanchasara — COMMENTED** [review]
Day11 => cant see painting section modal.

**Review by MilitPanchasara — COMMENTED** [review]
Day16 => apply proper validation for date. 02-30-2020 shows valid date.Current Logic is not sufficient to handle all cases.

**Review by MilitPanchasara — COMMENTED** [review]
Day14 => try to avoid opening files in new window (for example, you can show Day9/10 tasks with navigation instead opening in new tab)

**Comment by NirbhayDubey** [comment]
correction is done please review

**Pull request merged**
