### PR TITLE
REFS :50 and FIXES#50

### PR DESCRIPTION
**Pull request by anujpal82**
HERE THE LEARNING OF TODAY

Learned how to create branch.
how to checkout the branch.
how to resolve conflict.
difference between pull and fetch.
where and when to use gitignore.
how stage and stash are working.
reffered the tutorial video.

### CODE REVIEW

**Review by radixdt12020 — CHANGES_REQUESTED** [review]
day 4 resume should be attractive.ul tag should not in the capital letter

**Comment by radixdt12020** [comment]
when ever you are commiting please refer task id. next time onward please do it.

**Comment by radixdt12020** [comment]
#68 task pending Practice position properties static, relative, fixed and absolute.
	Suppose we have a div with specific height and width and we need to arrange more text into it. Use overflow properties.
	
	
	this two practice exes are pending from day5
	
	otherwise all okay. Complete this task in next commit

**Comment by radixdt12020** [comment]
#68 task pending Practice position properties static, relative, fixed and absolute.
	Suppose we have a div with specific height and width and we need to arrange more text into it. Use overflow properties.
	
	
	this two practice exes are pending from day5
	
	otherwise all okay. Complete this task in next commit

**Comment by anujpal82** [comment]
Okk mam

**Pull request merged**
