### PR TITLE
Till Day 16: Refs#98 Resolves#98 

### PR DESCRIPTION
**Pull request by viralgujarati**

### CODE REVIEW

**Review by Fi-ona — COMMENTED** [review]
Day3 - give number input type for age, salary
Day5 - Practice Exercise not proper

**Comment by viralgujarati** [comment]
> 
> 
> Day3 - give number input type for age, salary

Day3-resolved

**Review by Fi-ona — COMMENTED** [review]
Day8 - Photo Gallery missing

**Review by Fi-ona — COMMENTED** [review]
Day9 - float positions not defined

**Review by Fi-ona — COMMENTED** [review]
Day13 - mizuxe project collapse not working properly

**Review by Fi-ona — COMMENTED** [review]
Use OVERFLOW property

**Review by Fi-ona — COMMENTED** [review]
Day11 - Navbar collapse not working properly in small screen. Modals not working

**Review by Fi-ona — COMMENTED** [review]
Day9/10 - Modal, Alert and progressbar, tables and pagination, cards and media object files missing

**Comment by viralgujarati** [comment]
> 
> 
> Day9 - float positions not defined



> 
> 
> Day9 - float positions not defined

Day9- float position are in positions.html file

**Review by Fi-ona — COMMENTED** [review]
Day14 - Navigation not working

**Review by Fi-ona — COMMENTED** [review]
Day15 - Reset button not working

**Review by Fi-ona — COMMENTED** [review]
Day11 - Modals not implemented in paintings section

**Pull request closed without merging**
