### PR TITLE
Day2 #50,Day 11,12,13,14,15,16 :Creating pull to submit up to day16 still remain 14th day task

### PR DESCRIPTION
**Pull request by HarshitSampat**

### CODE REVIEW

**Review by Fi-ona — COMMENTED** [review]
Day3 - Use proper unordered list formatting
Day4 - Use proper naming convention in class names. Practice Exercise 3 not proper.
Day10 - Carousel images not loaded, collapse, tooltip, popover and modals not working

**Review by Fi-ona — COMMENTED** [review]
Day12 - Delete unwanted folder in Day12

**Review by Fi-ona — COMMENTED** [review]
Day13 - Collapse not working properly

**Review by Fi-ona — COMMENTED** [review]
Day15 - Practice Exercise 1 - sum of numbers remaining.
Day16 - Give proper validations. As per the code 09-09-0000 is valid date.
Practice Exercise 1 and 5 missing.

**Comment by HarshitSampat** [comment]
> Day3 - Use proper unordered list formatting
> Day4 - Use proper naming convention in class names. Practice Exercise 3 not proper.
> Day10 - Carousel images not loaded, collapse, tooltip, popover and modals not working.
> Day11 - Modals and navigation not working

Done

**Comment by HarshitSampat** [comment]
> Day12 - Delete unwanted folder in Day12



> Day13 - Collapse not working properly

Done

**Comment by HarshitSampat** [comment]
> Day13 - Collapse not working properly

Done

**Comment by HarshitSampat** [comment]
> Day15 - Practice Exercise 1 - sum of numbers remaining.
> Day16 - Give proper validations. As per the code 09-09-0000 is valid date.
> Practice Exercise 1 and 5 missing.

Done

**Review by radixdt12020 — COMMENTED** [review]
Data type should be capital

**Comment by HarshitSampat** [comment]
> Data type should be capital. Day1 Alter Statement not done

Complete Alter practice

**Pull request merged**
