### PR TITLE
day 11 to day 16

### PR DESCRIPTION
**Pull request by tarun345**

### CODE REVIEW

**Review by MilitPanchasara — COMMENTED** [review]
Day16 => Leap year condition not working (02-29-2021 shows valid date), also 04-31-2020 shows a valid date, plz update the algorithm.

**Review by MilitPanchasara — COMMENTED** [review]
Day15 => Reset the result also when reset is clicked.

**Review by MilitPanchasara — COMMENTED** [review]
Day11 => add smooth scrolling, image modal not working for Paintings section.

**Comment by tarun345** [comment]
> Day16 => Leap year condition not working (02-29-2021 shows valid date), also 04-31-2020 shows a valid date, plz update the algorithm.

done

**Comment by tarun345** [comment]
> Day11 => add smooth scrolling, image modal not working for Paintings section.

done

**Comment by tarun345** [comment]
> Day15 => Reset the result also when reset is clicked.

done

**Review by radixdt12020 — APPROVED** [review]

**Pull request merged**
